{% set version = "0.1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-janeaustenr
  version: {{ version|replace("-", "_") }}

source:
  fn: janeaustenr_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/janeaustenr_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/janeaustenr/janeaustenr_{{ version }}.tar.gz
  sha256: 992f6673653daf7010fe176993a01cd4127d9a88be428da8da7a28241826d6f3

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('janeaustenr')"  # [not win]
    - "\"%R%\" -e \"library('janeaustenr')\""  # [win]

about:
  home: https://github.com/juliasilge/janeaustenr
  license: MIT
  license_file: LICENSE
  summary: Full texts for Jane Austen's 6 completed novels, ready for text analysis. These novels
    are "Sense and Sensibility", "Pride and Prejudice", "Mansfield Park", "Emma", "Northanger
    Abbey", and "Persuasion".
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
