appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: HxhwSZpEyByhR9/p9qAUMI3QHEH32F1R0JwZIISkq/Oe9U2XCwRKpocoGWLmYbrSouUcz8dTBUmX3kV99ttxL1rGOY0pQSFPbL+XadLAyiv1QO+9OeNhWwfYLydtksBaDRMoDaUkgpw1PfvzmcFcwl5Pj+Z8rqh/3eKe56KSiQz4P85CwAogSam7bhv5W+neo/GKvKRVOUuhxs6rkfzAkwHIP8ungNXdEvgb5b5ogLZAA1Eprxj+JevqzjxsHegsvZsm1yfdW9km7mgtJjUOcPk+dIpfJh5VH5IGGNl5uZujOMHYjF92RakPzrtiP1v/ZUqhmUezfV2h67tIotwnHIL4Gt+IadOOctd+kULJ+ReRJEG3ktDFrg/3w2HuDawiTiYDtXaaPW3cTmOH5Rmf3PcsTcUMeLJP1HiQCMqRhYe6+NH2NZwDIE2XNAV38Atg9ftBwgoYKUP344y9CO0/slJvvSjyWwXh4HP2hxhSMHdP7oZre3ghlHrR+TUMRnPUSKYW50LV+EmgANV8DLGV8QrE5yZuKsumnG/E7OfZB9nrL5fVt6+mWHwX35MxZYCqDdyzSPI1nbNWIgt+oPq2JyRnWc/vdSvdBa0IREG5w/aq2ZsQslOCg4caZ2thZ0HpD3LAUUHgTOTuXZ6Rrbjh7wsKb/A9llTncINmLBv8CFo=
